name: Awesome Action
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Awesome Action
        env:
          awesome: ${{ secrets.AMAZING_SECRET }}
        shell: bash
        run: |
          echo "Hello World"
          echo "This is an awesome action"
          echo The secret is $awesome
          